# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 05:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('dx', models.FloatField()),
                ('dy', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.CharField(max_length=50)),
                ('gmt_start', models.DateField()),
                ('gmt_end', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('item_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.CharField(max_length=50)),
                ('level_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('video_url', models.URLField()),
                ('img_url', models.URLField()),
                ('test', models.TextField()),
                ('number_answer', models.CharField(max_length=50)),
                ('h5_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('time', models.IntegerField()),
                ('good', models.IntegerField()),
                ('distance', models.FloatField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPartyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnchor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('completed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('item_id', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('visited', models.BooleanField()),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
