# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160626_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detail_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
