# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-13 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160413_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('gmt_created', models.DateField()),
                ('gmt_modified', models.DateField()),
                ('username', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('head_url', models.URLField()),
                ('sex', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='anchor',
            name='anchor_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='useranchor',
            name='anchor_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='useranchor',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='item_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usermap',
            name='map_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usermap',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
