# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_loginreward_userloginreward'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='loginreward',
            index_together=set([('gmt_start', 'gmt_stop')]),
        ),
    ]
