# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160701_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginreward',
            old_name='gmt_stop',
            new_name='gmt_end',
        ),
        migrations.AlterIndexTogether(
            name='loginreward',
            index_together=set([('gmt_start', 'gmt_end')]),
        ),
    ]
