# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 15:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20160701_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='LoginReward',
            new_name='LoginAward',
        ),
        migrations.RemoveField(
            model_name='userloginreward',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='userloginreward',
            name='user',
        ),
        migrations.RenameField(
            model_name='loginaward',
            old_name='amount',
            new_name='coin',
        ),
        migrations.DeleteModel(
            name='UserLoginReward',
        ),
        migrations.AddField(
            model_name='userloginaward',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_login_awards', to='api.LoginAward'),
        ),
        migrations.AddField(
            model_name='userloginaward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_login_awards', to=settings.AUTH_USER_MODEL),
        ),
    ]
