# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CEE' do
    pod 'Realm'
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'ReactiveCocoa', '~> 2.5'
    pod 'SDWebImage'
    pod 'RDVTabBarController'
    pod 'AVOSCloud'
    pod 'AVOSCloudCrashReporting'
    pod 'AVOSCloudIM'
    pod 'ShareSDK3'
    pod 'MOBFoundation'
    pod 'ShareSDK3/ShareSDKPlatforms/QQ'
    pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
    pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
    pod 'ABMenuTableViewCell'
    pod 'AJWValidator'
    pod 'JSONModel'
end

