# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CEE' do
    pod 'Realm'
    pod 'AFNetworking'
    pod 'ReactiveCocoa'
    pod 'SDWebImage'
    pod 'RDVTabBarController'
    pod 'AVOSCloud'
    pod 'AVOSCloudCrashReporting'
end

